### ISSUE TITLE
Phenotype decoding

### ISSUE THREAD

**Issue by kaenova** [ShinyQ/Tugas-Pengantar-AI-1_Genetic-Algorithm#1]
![image](https://user-images.githubusercontent.com/61568092/111744428-cfb6eb00-88bd-11eb-98b3-d82f1c0931aa.png)

I think you got it wrong on the return
it should be
```python
return limit[0] + (((limit[1] - limit[0]) / pembagi) * kali)
```

**Comment by ShinyQ** [comment]
Ah yes, Thank you so much for the correction.
